const express = require('express')
const serverless = require('serverless-http')
const app = express()
app.get('/hell', (req, res) => res.send('Hello World'))
app.listen(3000, () => console.log('Running on port 3000'))
module.exports.handler = serverless(app)